apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jumps
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jumps
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 90
