apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jumps-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - jumps.io
    - www.jumps.io
    secretName: jumps-tls
  defaultBackend:
    service:
      name: jumps
      port:
        number: 81
  rules:
  - host: jumps.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jumps
            port:
              number: 81
  - host: www.jumps.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jumps
            port:
              number: 81
